Add an option to override laterality test for JTT
psychoinformatics-de/sfb1451_data_entry pull request #26
Opened 2022-03-17 11:36 UTC by mslw

Added a switch (turned off by default) which disables laterality checking for JTT.

@christian-monch the JS part does what I would expect it to do, but I wasn't able to verify the server part - my intuition is that the checkbox shouldn't produce any additional data that gets passed to the server (and json file stored by DataLad) but that might be wrong, could you check it?

2022-03-17 13:51 UTC, christian-monch requested changes
LGTM, there is

2022-03-17 13:51 UTC, christian-monch commented on entry.html
> +	  <div class="col-lg-5"> Lateralitätsprüfung Abheben </div>
It should read: "Lateralitätsprüfung aufheben"

2022-03-17 14:21 UTC, mslw commented on entry.html
> +	  <div class="col-lg-5"> Lateralitätsprüfung Abheben </div>
Heh, there shows my German knowledge :laughing: Corrected.

2022-03-17 14:25 UTC, mslw commented
Fixed the wording. Before merging let's maybe wait for confirmation from @VeronikaWu whether that matches her expectations, and whether only JTT needs this override.

2022-03-17 15:36 UTC, VeronikaWu commented
This looks great. Until now, we need it only for JTT, but it possibly could occur for the other tests with laterality check as well. Depending on what would be easier to implement, the same check boxes or one checkbox for all affected tests would be great (but not urgent). Thank you so much for your quick help.

2022-03-21 11:38 UTC, mslw commented
Thank you for the feedback, @VeronikaWu. I applied the same logic to other tests (form sections) that were check for laterality. So now each of these gets a slider that disables the laterality check for this test:
- Motorische Testung: Basisfähigkeiten
- Purdue Pegboard Test
- Jebsen Taylor Hand Function Test (JTT)
- Action Research Arm Test (ARAT)

@christian-monch I think this is ready to merge and deploy, although as always would be good if you checked for mistakes.

2022-03-24 12:27 UTC, christian-monch approved these changes

2022-03-24 12:31 UTC, merged