WIP: Implement local save and load buttons
psychoinformatics-de/sfb1451_data_entry pull request #28
Opened 2022-06-10 18:37 UTC by mslw

This is work in progress towards https://github.com/psychoinformatics-de/sfb1451_org/issues/33

2022-06-27 11:53 UTC, christian-monch commented
If "Probanden-Pseudonym" is not set, a file name `json` is locally saved.

Either saving should be refused, if "Probanden-Pseudonym" is unset, or there should be the possibility to choose a name manually in case it is unset

2022-06-27 14:14 UTC, christian-monch requested changes
Generally looks good to me. Can be merged if the comments are addressed.

2022-06-27 14:14 UTC, christian-monch commented on entry.html
> +	contentObj['subject-group'] = getStringContent('subject-group');  // not present in getContentString
Just for my understanding: why is `subject-group` not present in `getContentString()`-results?

2022-06-27 14:14 UTC, christian-monch commented on entry.html
> +	let fname = savedObject['subject-pseudonym'] + ".json"  // use Pseudonym as filename
If `subject-pseudonym` is not set, `fname` will be `.json` (there is also a comment in the PR discussion). Maybe decline to save without `subject-pseudonym` or ask for a value?

2022-06-27 14:14 UTC, christian-monch commented on entry.html
> +	return false;
Maybe remove element `a` again?

2022-06-27 14:14 UTC, christian-monch commented on entry.html
> +
Generally it would be nice if you could unify tab and space, more precisly, replace tabs with 4 spaces

2022-06-27 14:30 UTC, mslw commented on entry.html
> +	contentObj['subject-group'] = getStringContent('subject-group');  // not present in getContentString
It wasn't when I started. The old `getContentString` explicitly defines an array with a list of ids, and `subject-group` wasn't there. May be a simple omission.

I chose to tack it on to contentObj (for saving) rather then change the existng getContentString behaviour.

2022-06-28 13:17 UTC, mslw commented on entry.html
> +	let fname = savedObject['subject-pseudonym'] + ".json"  // use Pseudonym as filename
I'm going for "decline to save" - it makes little sense to save records not attributed to any subject.

I also don't know an easy way to ask for value. I found [showSaveFilePicker](https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker) in JS, but it's new and currently supported only by Chromium-based browsers.

2022-06-28 13:32 UTC, mslw commented on entry.html
> +
I thought I knew my editor, but apparently not... I'll clean it up (probably I'll run prettier on the script blocks).

2022-06-28 16:16 UTC, mslw commented
I made the suggested changes (commented above). I used prettier to clean up not only tabs, but also quotes, semicolons, spaces, and the like.

2022-06-29 09:20 UTC, christian-monch approved these changes
LGTM, will merge
Thx a lot

2022-06-29 09:20 UTC, merged